version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    environment:
      - DB_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres
      - FAISS_INDEX_PATH=/faiss_indices
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./faiss_indices:/faiss_indices

  frontend:
    build: ./frontend/idea-code-release-frontend  # Путь к фронтенду (нужно создать Dockerfile для фронта)
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  rag-model:
    build: ./ai
    container_name: rag_model
    depends_on:
      - ollama
    environment:
      - FAISS_INDEX_PATH=/faiss_indices
      - OLLAMA_API=http://ollama:11434
    volumes:
      - ./faiss_indices:/faiss_indices

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always
    entrypoint: sh -c "ollama serve & ollama pull llama3:8b && wait"

volumes:
  postgres_data:
  ollama_data:

networks:
  app-network:
    driver: bridge